### ISSUE TITLE
失效

### ISSUE THREAD

**Issue by mdnzc** [aowubulao/auto-cpdaily#16]
12:40:29.806 [main] ERROR daily.AutoDailyCp - 打卡失败，错误信息：

java.lang.StringIndexOutOfBoundsException: String index out of range: -1

  at java.lang.String.substring(String.java:1967)

  at daily.request.LoginRequest.handleCookie(LoginRequest.java:75)

  at daily.request.LoginRequest.login(LoginRequest.java:69)

  at daily.AutoDailyCp.startApplication(AutoDailyCp.java:50)

  at daily.AutoDailyCp.mainHandler(AutoDailyCp.java:31)

  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

  at java.lang.reflect.Method.invoke(Method.java:498)

  at scfinternal.EventHandlerLoader$BaseMethodRequestHandler.handlerRequest(EventHandlerLoader.java:225)

  at bootstrap.eventInvoke(bootstrap.java:164)

  at bootstrap.main(bootstrap.java:229)

**Comment by mdnzc** [comment]
之前也有过失效，不确定是否是相同错误原因，不知道是否是后台更新了

**Comment by BiuBiu2323** [comment]
简单修复了一下 https://github.com/BiuBiu2323/auto-cpdaily.git

**Comment by aowubulao** [comment]
> 简单修复了一下 https://github.com/BiuBiu2323/auto-cpdaily.git

感谢PR！

**Comment by BiuBiu2323** [comment]
> > 简单修复了一下https://github.com/BiuBiu2323/auto-cpdaily.git
> 
> 感谢PR！

客气啦
