### ISSUE TITLE
签到失败了

### ISSUE THREAD

**Issue by nickkking** [aowubulao/auto-cpdaily#18]
START RequestId:2c1cb061-8499-441a-b9f1-dcb36ff5d723

13:32:19.960 [main] INFO daily.AutoDailyCp - 程序启动... By Neo

13:32:19.964 [main] INFO daily.AutoDailyCp - 程序初始化中...

13:32:21.652 [main] ERROR daily.AutoDailyCp - 打卡失败，错误信息：

java.lang.StringIndexOutOfBoundsException: String index out of range: -1

at java.lang.String.substring(String.java:1967)

at daily.request.LoginRequest.handleCookie(LoginRequest.java:75)

at daily.request.LoginRequest.login(LoginRequest.java:69)

at daily.AutoDailyCp.startApplication(AutoDailyCp.java:50)

at daily.AutoDailyCp.mainHandler(AutoDailyCp.java:31)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:498)

at scfinternal.EventHandlerLoader$BaseMethodRequestHandler.handlerRequest(EventHandlerLoader.java:225)

at bootstrap.eventInvoke(bootstrap.java:164)

at bootstrap.main(bootstrap.java:229) 

END RequestId:2c1cb061-8499-441a-b9f1-dcb36ff5d723

Report RequestId:2c1cb061-8499-441a-b9f1-dcb36ff5d723 Duration:2095ms Memory:256MB MemUsage:117.804688MB

**Comment by aowubulao** [comment]
已经更新了，下载新版即可https://github.com/aowubulao/auto-cpdaily/releases/tag/v1.3.3
