### ISSUE TITLE
晨间打卡错误，望修复

### ISSUE THREAD

**Issue by 13631181823** [aowubulao/auto-cpdaily#19]
START RequestId:527b411c-d125-4074-a351-e7887181840b

00:05:03.690 [main] INFO daily.SignApplication - 程序启动... By Neo

00:05:03.703 [main] INFO daily.SignApplication - 程序初始化中...

00:05:05.258 [main] INFO daily.SignApplication - 今日校园登陆成功

00:05:05.303 [main] ERROR daily.SignApplication - 打卡失败，错误信息：

cn.hutool.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]

at cn.hutool.json.JSONTokener.syntaxError(JSONTokener.java:385)

at cn.hutool.json.JSONObject.init(JSONObject.java:697)

at cn.hutool.json.JSONObject.init(JSONObject.java:684)

at cn.hutool.json.JSONObject.init(JSONObject.java:666)

**Comment by 13631181823** [comment]
求更新！最近不大好用了，老失败。

**Comment by aowubulao** [comment]
修复了

**Comment by 13631181823** [comment]
> 修复了

感谢更新！！！
