### ISSUE TITLE
关于打卡失败-目前已修复

### ISSUE THREAD

**Issue by aowubulao** [aowubulao/auto-cpdaily#21]
~~原因是登录接口：http://authserverxg.swu.edu.cn
目前无法访问，不清楚是维护还是学校主动关闭~~

**--2021.5.20--
今天已经适配了，可能会出现BUG，如果使用中遇到了请提出来**

**关于更新**
原先的密码是身份证后六位，需要使用新的密码

需要进行的操作：
1、在今日校园登录界面：使用学工号登录
2、使用学号+身份证后六位登录
3、会引导设置新的密码
4、将本程序的密码更换为新设置的密码即可

**Comment by mdnzc** [comment]
{"errorCode":-1,"errorMessage":"Invoking task timed out after 20 seconds","statusCode":433}
10am,感觉不会开了

**Comment by 812735341** [comment]
现在是可以使用了吗？

**Comment by aowubulao** [comment]
> 现在是可以使用了吗？

还不能，界面可以进入但无法登陆，估计是在DEBUG之类的

**Comment by 812735341** [comment]
弱弱的问一句，大概多久能恢复使用呀？

**Comment by 812735341** [comment]
这个还有恢复的可能性嘛？

**Comment by aowubulao** [comment]
> 这个还有恢复的可能性嘛？

今天恢复了，是学校换了新版，正在适配

**Comment by 812735341** [comment]
请问下有些上传上去后显示
08:18:15.498 [main] INFO daily.SignApplication - 程序初始化中...

08:18:16.755 [main] INFO daily.SignApplication - 今日校园登陆成功

08:18:16.783 [main] ERROR daily.SignApplication - 打卡失败，错误信息：

cn.hutool.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]

  at cn.hutool.json.JSONTokener.syntaxError(JSONTokener.java:385)

  at cn.hutool.json.JSONObject.init(JSONObject.java:697)

  at cn.hutool.json.JSONObject.init(JSONObject.java:684)

  at cn.hutool.json.JSONObject.init(JSONObject.java:666)

  at cn.hutool.json.JSONObject.<init>(JSONObject.java:189)

  at cn.hutool.json.JSONObject.<init>(JSONObject.java:165)

  at cn.hutool.json.JSONObject.<init>(JSONObject.java:147)

  at cn.hutool.json.JSONObject.<init>(JSONObject.java:130)

  at cn.hutool.json.JSONUtil.parseObj(JSONUtil.java:67)

  at daily.request.SignRequest.getResponseJson(SignRequest.java:88)

  at daily.request.SignRequest.getMessage(SignRequest.java:59)

  at daily.SignApplication.sign(SignApplication.java:78)

  at daily.SignApplication.startApplication(SignApplication.java:71)

  at daily.SignApplication.start(SignApplication.java:38)

  at daily.AutoDailyCp.mainHandler(AutoDailyCp.java:28)

  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

  at java.lang.reflect.Method.invoke(Method.java:497)

  at scfinternal.EventHandlerLoader$BaseMethodRequestHandler.handlerRequest(EventHandlerLoader.java:225)

  at bootstrap.eventInvoke(bootstrap.java:164)

  at bootstrap.main(bootstrap.java:229)


END RequestId: 1b99325b-9466-4597-8998-1362e1fb0927

Report RequestId: 1b99325b-9466-4597-8998-1362e1fb0927 Duration:2555ms Memory:256MB MemUsage:112.645MB

**Comment by aowubulao** [comment]
> 请问下有些上传上去后显示
> 08:18:15.498 [main] INFO daily.SignApplication - 程序初始化中...
> 
> 08:18:16.755 [main] INFO daily.SignApplication - 今日校园登陆成功
> 
> 08:18:16.783 [main] ERROR daily.SignApplication - 打卡失败，错误信息：
> 
> cn.hutool.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
> 
> at cn.hutool.json.JSONTokener.syntaxError(JSONTokener.java:385)
> 
> at cn.hutool.json.JSONObject.init(JSONObject.java:697)
> 
> at cn.hutool.json.JSONObject.init(JSONObject.java:684)
> 
> at cn.hutool.json.JSONObject.init(JSONObject.java:666)
> 
> at cn.hutool.json.JSONObject.(JSONObject.java:189)
> 
> at cn.hutool.json.JSONObject.(JSONObject.java:165)
> 
> at cn.hutool.json.JSONObject.(JSONObject.java:147)
> 
> at cn.hutool.json.JSONObject.(JSONObject.java:130)
> 
> at cn.hutool.json.JSONUtil.parseObj(JSONUtil.java:67)
> 
> at daily.request.SignRequest.getResponseJson(SignRequest.java:88)
> 
> at daily.request.SignRequest.getMessage(SignRequest.java:59)
> 
> at daily.SignApplication.sign(SignApplication.java:78)
> 
> at daily.SignApplication.startApplication(SignApplication.java:71)
> 
> at daily.SignApplication.start(SignApplication.java:38)
> 
> at daily.AutoDailyCp.mainHandler(AutoDailyCp.java:28)
> 
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 
> at java.lang.reflect.Method.invoke(Method.java:497)
> 
> at scfinternal.EventHandlerLoader$BaseMethodRequestHandler.handlerRequest(EventHandlerLoader.java:225)
> 
> at bootstrap.eventInvoke(bootstrap.java:164)
> 
> at bootstrap.main(bootstrap.java:229)
> 
> END RequestId: 1b99325b-9466-4597-8998-1362e1fb0927
> 
> Report RequestId: 1b99325b-9466-4597-8998-1362e1fb0927 Duration:2555ms Memory:256MB MemUsage:112.645MB



> 请问下有些上传上去后显示
> 08:18:15.498 [main] INFO daily.SignApplication - 程序初始化中...
> 
> 08:18:16.755 [main] INFO daily.SignApplication - 今日校园登陆成功
> 
> 08:18:16.783 [main] ERROR daily.SignApplication - 打卡失败，错误信息：
> 
> cn.hutool.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
> 
> at cn.hutool.json.JSONTokener.syntaxError(JSONTokener.java:385)
> 
> at cn.hutool.json.JSONObject.init(JSONObject.java:697)
> 
> at cn.hutool.json.JSONObject.init(JSONObject.java:684)
> 
> at cn.hutool.json.JSONObject.init(JSONObject.java:666)
> 
> at cn.hutool.json.JSONObject.(JSONObject.java:189)
> 
> at cn.hutool.json.JSONObject.(JSONObject.java:165)
> 
> at cn.hutool.json.JSONObject.(JSONObject.java:147)
> 
> at cn.hutool.json.JSONObject.(JSONObject.java:130)
> 
> at cn.hutool.json.JSONUtil.parseObj(JSONUtil.java:67)
> 
> at daily.request.SignRequest.getResponseJson(SignRequest.java:88)
> 
> at daily.request.SignRequest.getMessage(SignRequest.java:59)
> 
> at daily.SignApplication.sign(SignApplication.java:78)
> 
> at daily.SignApplication.startApplication(SignApplication.java:71)
> 
> at daily.SignApplication.start(SignApplication.java:38)
> 
> at daily.AutoDailyCp.mainHandler(AutoDailyCp.java:28)
> 
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 
> at java.lang.reflect.Method.invoke(Method.java:497)
> 
> at scfinternal.EventHandlerLoader$BaseMethodRequestHandler.handlerRequest(EventHandlerLoader.java:225)
> 
> at bootstrap.eventInvoke(bootstrap.java:164)
> 
> at bootstrap.main(bootstrap.java:229)
> 
> END RequestId: 1b99325b-9466-4597-8998-1362e1fb0927
> 
> Report RequestId: 1b99325b-9466-4597-8998-1362e1fb0927 Duration:2555ms Memory:256MB MemUsage:112.645MB

要先进今日校园学工号登录修改新的密码，原先的身份证后六位不能使用了

**Comment by loveykx** [comment]
现在还报这个错误怎么办？
START RequestId: d651bd9d-4b30-4835-a560-6227ea1d5f85

Init Report RequestId: d651bd9d-4b30-4835-a560-6227ea1d5f85 Coldstart: 921ms (PullCode: 214ms InitRuntime: 9ms InitFunction: 698ms) Memory: 256MB MemUsage: 37.11MB

14:00:02.419 [main] INFO daily.SignApplication - 程序启动... By Neo

14:00:02.424 [main] INFO daily.SignApplication - 程序初始化中...

14:00:03.381 [main] INFO daily.SignApplication - 今日校园登陆成功

14:00:03.427 [main] ERROR daily.SignApplication - 打卡失败，错误信息：

cn.hutool.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]

at cn.hutool.json.JSONTokener.syntaxError(JSONTokener.java:385)

at cn.hutool.json.JSONObject.init(JSONObject.java:697)

at cn.hutool.json.JSONObject.init(JSONObject.java:684)

at cn.hutool.json.JSONObject.init(JSONObject.java:666)

at cn.hutool.json.JSONObject.<init>(JSONObject.java:189)

at cn.hutool.json.JSONObject.<init>(JSONObject.java:165)

at cn.hutool.json.JSONObject.<init>(JSONObject.java:147)

at cn.hutool.json.JSONObject.<init>(JSONObject.java:130)

at cn.hutool.json.JSONUtil.parseObj(JSONUtil.java:67)

at daily.request.SignRequest.getResponseJson(SignRequest.java:88)

at daily.request.SignRequest.getMessage(SignRequest.java:59)

at daily.SignApplication.sign(SignApplication.java:78)

at daily.SignApplication.startApplication(SignApplication.java:71)

at daily.SignApplication.start(SignApplication.java:38)

at daily.AutoDailyCp.mainHandler(AutoDailyCp.java:28)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:497)

at scfinternal.EventHandlerLoader$BaseMethodRequestHandler.handlerRequest(EventHandlerLoader.java:218)

at bootstrap.eventInvoke(bootstrap.java:150)

at bootstrap.main(bootstrap.java:224)

Response RequestId: d651bd9d-4b30-4835-a560-6227ea1d5f85 RetMsg: null

END RequestId: d651bd9d-4b30-4835-a560-6227ea1d5f85

Report RequestId: d651bd9d-4b30-4835-a560-6227ea1d5f85 Duration: 1132ms Memory: 256MB MemUsage: 57.88MB
